### ISSUE TITLE
pip install -r ~/devel/my_ocrd_workflow/requirements-ppn2ocr.txt seems to need scikit-build

### ISSUE THREAD

**Issue by mikegerber** [mikegerber/my_ocrd_workflow#22]
@cneud reports:

> Ich notiers nur kurz hier als Erinnerung...damit für https://github.com/mikegerber/my_ocrd_workflow#ppn2ocr opencv-headless gebaut wird musste ich noch scikit-build per pip installieren

~~~
Collecting opencv-python-headless (from ocrd->-r /home/cnd/tmp/dev/qurator/my_ocrd_workflow/requirements-ppn2ocr.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/2f/b4/2ddaaecc332e6ddafb7726abb6139955a99282afe5f370930890bb572707/opencv-python-headless-4.4.0.42.tar.gz (88.9MB)
    100% |████████████████████████████████| 88.9MB 18kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wx36s1mb/opencv-python-headless/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'   
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wx36s1mb/opencv-python-headless/
~~~

**Comment by mikegerber** [comment]
It's this issue from the [opencv-python FAQ](https://pypi.org/project/opencv-python/):
> Q: Pip install fails with ModuleNotFoundError: No module named 'skbuild'?
> Since opencv-python version 4.3.0.*, manylinux1 wheels were replaced by manylinux2014 wheels. If your pip is too old, it will try to use the new source distribution introduced in 4.3.0.38 to manually build OpenCV because it does not know how to install manylinux2014 wheels. However, source build will also fail because of too old pip because it does not understand build dependencies in pyproject.toml. To use the new manylinux2014 pre-built wheels (or to build from source), your pip version must be >= 19.3. Please upgrade pip with pip install --upgrade pip.

TL&DR: Always upgrade pip first because otherwise bad things happen. In this case, both the binary and the source install fails because of an old pip.

**Comment by mikegerber** [comment]
Side note: This was probably triggered using Ubuntu's system pip, so _not_ in a venv. Always use a venv unless you know what you're doing. (And if not, upgrade pip!)

**Comment by mikegerber** [comment]
https://github.com/mikegerber/my_ocrd_workflow/blob/master/README.md now mentions this issue and the fix (upgrade pip)!
